import React from 'react';
import { FileText, Download, Eye, Clock } from 'lucide-react';
import { useState } from 'react';
import ViewReportModal from './modals/ViewReportModal';

const ReportHistory = ({ data }) => {
    const [selectedReport, setSelectedReport] = useState(null);
    const [isModalOpen, setIsModalOpen] = useState(false);

    const handleViewReport = (report) => {
        setSelectedReport(report);
        setIsModalOpen(true);
    };

    const handleCloseModal = () => {
        setIsModalOpen(false);
        setSelectedReport(null);
    };

    if (!data) return <div className="p-4 text-center text-gray-500">No report history available</div>;

    return (
        <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden animate-in fade-in duration-500">
            <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-700 flex justify-between items-center">
                <h3 className="font-bold text-slate-800 dark:text-white flex items-center gap-2">
                    <Clock size={18} className="text-slate-400" /> Recent Reports
                </h3>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full text-sm text-left">
                    <thead className="text-xs text-slate-500 uppercase bg-slate-50 dark:bg-slate-900 border-b border-slate-100 dark:border-slate-700">
                        <tr>
                            <th className="px-6 py-3 font-semibold">Report Name</th>
                            <th className="px-6 py-3 font-semibold">Generated By</th>
                            <th className="px-6 py-3 font-semibold">Date</th>
                            <th className="px-6 py-3 font-semibold">Filters Used</th>
                            <th className="px-6 py-3 font-semibold text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                        {data.map((row) => (
                            <tr key={row.id} className="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors">
                                <td className="px-6 py-3 font-medium text-slate-900 dark:text-white flex items-center gap-3">
                                    <div className="p-2 bg-blue-50 text-blue-600 rounded-lg">
                                        <FileText size={16} />
                                    </div>
                                    {row.name}
                                </td>
                                <td className="px-6 py-3 text-slate-600 dark:text-slate-400">{row.user}</td>
                                <td className="px-6 py-3 text-slate-600 dark:text-slate-400">{row.date}</td>
                                <td className="px-6 py-3 text-slate-500 dark:text-slate-500 italic">{row.filters}</td>
                                <td className="px-6 py-3 text-right">
                                    <div className="flex justify-end gap-2">
                                        <button
                                            onClick={() => handleViewReport(row)}
                                            className="p-1.5 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors"
                                            title="View"
                                        >
                                            <Eye size={16} />
                                        </button>
                                        <button className="p-1.5 text-slate-500 hover:text-green-600 hover:bg-green-50 rounded transition-colors" title="Download">
                                            <Download size={16} />
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>


            <ViewReportModal
                isOpen={isModalOpen}
                onClose={handleCloseModal}
                report={selectedReport}
            />
        </div >
    );
};

export default ReportHistory;
