import React from 'react';
import { X, FileText, Calendar, User, Filter, Download } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const ViewReportModal = ({ isOpen, onClose, report }) => {
    if (!isOpen || !report) return null;

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl w-full max-w-2xl overflow-hidden border border-slate-200 dark:border-slate-700"
                >
                    {/* Header */}
                    <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-700 flex justify-between items-center bg-slate-50/50 dark:bg-slate-900/50">
                        <div>
                            <h3 className="font-bold text-slate-800 dark:text-white flex items-center gap-2 text-lg">
                                <FileText size={20} className="text-blue-600" />
                                Report Details
                            </h3>
                            <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
                                Viewing report ID: #{report.id}
                            </p>
                        </div>
                        <button
                            onClick={onClose}
                            className="p-2 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-full text-slate-500 transition-colors"
                        >
                            <X size={20} />
                        </button>
                    </div>

                    {/* Content */}
                    <div className="p-6 space-y-6">
                        {/* Report Name Section */}
                        <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-xl border border-blue-100 dark:border-blue-800">
                            <label className="text-xs font-bold text-blue-600 dark:text-blue-400 uppercase tracking-wider">Report Name</label>
                            <p className="text-xl font-bold text-slate-900 dark:text-white mt-1">{report.name}</p>
                        </div>

                        {/* Metadata Grid */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="flex items-start gap-3 p-3 rounded-lg border border-slate-100 dark:border-slate-700">
                                <div className="p-2 bg-slate-100 dark:bg-slate-800 rounded-lg text-slate-500">
                                    <User size={18} />
                                </div>
                                <div>
                                    <label className="text-xs font-semibold text-slate-500 uppercase">Generated By</label>
                                    <p className="font-medium text-slate-800 dark:text-slate-200">{report.user}</p>
                                </div>
                            </div>
                            <div className="flex items-start gap-3 p-3 rounded-lg border border-slate-100 dark:border-slate-700">
                                <div className="p-2 bg-slate-100 dark:bg-slate-800 rounded-lg text-slate-500">
                                    <Calendar size={18} />
                                </div>
                                <div>
                                    <label className="text-xs font-semibold text-slate-500 uppercase">Date Generated</label>
                                    <p className="font-medium text-slate-800 dark:text-slate-200">{report.date}</p>
                                </div>
                            </div>
                        </div>

                        {/* Filters Used */}
                        <div>
                            <h4 className="text-sm font-bold text-slate-800 dark:text-white mb-3 flex items-center gap-2">
                                <Filter size={16} /> Filters Applied
                            </h4>
                            <div className="bg-slate-50 dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
                                <p className="text-sm text-slate-600 dark:text-slate-300 font-mono">
                                    {report.filters}
                                </p>
                            </div>
                        </div>

                        {/* Preview Placeholder */}
                        <div className="border-t border-slate-100 dark:border-slate-700 pt-4">
                            <p className="text-xs text-center text-slate-400 italic">
                                This is a summary view. To see full data, please download the report.
                            </p>
                        </div>
                    </div>

                    {/* Footer */}
                    <div className="px-6 py-4 bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-700 flex justify-end gap-3">
                        <button
                            onClick={onClose}
                            className="px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-lg transition-colors"
                        >
                            Close
                        </button>
                        <button className="px-4 py-2 text-sm font-medium text-black bg-blue-600 hover:bg-blue-700 rounded-lg shadow-sm flex items-center gap-2 transition-colors">
                            <Download size={16} /> Download PDF
                        </button>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
};

export default ViewReportModal;
