/**
 * Finance Report Export Utility
 * Supports: PDF (print), Excel (CSV/XLSX via data-uri), RTF
 *
 * Usage:
 *   exportReport({ title, headers, rows, format: 'pdf'|'excel'|'rtf', filename? })
 *
 * rows: array of arrays (matching headers order)
 * or pass { tableId } to export an existing HTML table by DOM id.
 */

import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

const fmtCurrency = (v) =>
    new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(v ?? 0);

/** Export via jsPDF - Perfectly formatted for printing or saving */
export function exportToPDF({ title, subtitle = '', headers, rows, filename = 'report' }) {
    const doc = new jsPDF('p', 'pt', 'a4');
    const totalPagesExp = '{total_pages_count_string}';
    
    const tableData = rows.map(row => 
        row.map(cell => {
            if (typeof cell === 'number') {
                return fmtCurrency(cell);
            }
            return cell ?? '';
        })
    );

    const institutionName = "Fahari Academy";
    
    const printDate = new Date();
    // E.g., 1st June 2026
    const day = printDate.getDate();
    const suffix = ["th", "st", "nd", "rd"][(day % 10 > 3 || Math.floor(day % 100 / 10) === 1) ? 0 : day % 10];
    const month = printDate.toLocaleString('en-GB', { month: 'long' });
    const year = printDate.getFullYear();
    const time = printDate.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true }).toLowerCase();
    
    const printedOnStr = `Printed On : ${day}${suffix} ${month} ${year} ${time}`;

    doc.autoTable({
        head: [headers],
        body: tableData,
        startY: 110,
        theme: 'striped',
        headStyles: { fillColor: [30, 64, 175], textColor: 255, fontSize: 10, halign: 'left' },
        styles: { fontSize: 9, cellPadding: 5 },
        didDrawPage: function (data) {
            // Header
            doc.setFontSize(16);
            doc.setTextColor(30, 41, 59);
            doc.setFont("helvetica", "bold");
            doc.text(institutionName, data.settings.margin.left, 40);

            doc.setFontSize(9);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(100, 116, 139);
            const printedOnWidth = doc.getStringUnitWidth(printedOnStr) * doc.internal.getFontSize() / doc.internal.scaleFactor;
            doc.text(printedOnStr, doc.internal.pageSize.width - data.settings.margin.right - printedOnWidth, 40);

            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(30, 64, 175);
            doc.text(title, data.settings.margin.left, 70);

            if (subtitle) {
                doc.setFontSize(10);
                doc.setFont("helvetica", "normal");
                doc.setTextColor(100, 116, 139);
                doc.text(subtitle, data.settings.margin.left, 85);
            }

            doc.setDrawColor(200, 200, 200);
            doc.setLineWidth(1);
            doc.line(data.settings.margin.left, 95, doc.internal.pageSize.width - data.settings.margin.right, 95);

            // Footer
            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
            
            doc.setDrawColor(200, 200, 200);
            doc.setLineWidth(1);
            doc.line(data.settings.margin.left, pageHeight - 35, pageSize.width - data.settings.margin.right, pageHeight - 35);
            
            doc.setFontSize(8);
            doc.setFont("helvetica", "italic");
            doc.setTextColor(150, 150, 150);
            doc.text("Generated by Fahari School Management System", data.settings.margin.left, pageHeight - 20);

            doc.setFont("helvetica", "normal");
            const str = `Page ${doc.internal.getNumberOfPages()} of ${totalPagesExp}`;
            const strWidth = doc.getStringUnitWidth(str) * doc.internal.getFontSize() / doc.internal.scaleFactor;
            doc.text(str, pageSize.width - data.settings.margin.right - strWidth, pageHeight - 20);
        },
        margin: { top: 110, bottom: 50, left: 40, right: 40 }
    });

    if (typeof doc.putTotalPages === 'function') {
        doc.putTotalPages(totalPagesExp);
    }
    
    // Open in new tab so user can immediately view/print
    const blobUrl = doc.output('bloburl');
    window.open(blobUrl, '_blank');
}

/** Export to CSV (opens as Excel) */
export function exportToExcel({ title, headers, rows, filename = 'report' }) {
    const escape = (v) => {
        const s = String(v ?? '').replace(/"/g, '""');
        return /[,"\n]/.test(s) ? `"${s}"` : s;
    };

    const lines = [
        `"${title}"`,
        '',
        headers.map(escape).join(','),
        ...rows.map((row) => row.map(escape).join(',')),
    ];

    const csv = lines.join('\r\n');
    const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.csv`;
    a.click();
    URL.revokeObjectURL(url);
}

/** Export to RTF */
export function exportToRTF({ title, headers, rows, filename = 'report' }) {
    const rtfEscape = (s) =>
        String(s ?? '')
            .replace(/\\/g, '\\\\')
            .replace(/\{/g, '\\{')
            .replace(/\}/g, '\\}')
            .replace(/[^\x00-\x7F]/g, (c) => `\\u${c.charCodeAt(0)}?`);

    const colCount = headers.length;
    const colWidth = Math.floor(9000 / colCount);

    const cellDef = Array(colCount).fill(`\\cellx${colWidth}`).map((c, i) => `\\cellx${(i + 1) * colWidth}`).join('');

    const headerRow = `{\\trowd\\trgaph108\\trleft0 ${cellDef}\\intbl ${headers.map((h) => `{\\b ${rtfEscape(h)}}\\cell`).join(' ')}\\row}`;

    const dataRows = rows
        .map(
            (row) =>
                `{\\trowd\\trgaph108\\trleft0 ${cellDef}\\intbl ${row.map((c) => `${rtfEscape(c)}\\cell`).join(' ')}\\row}`
        )
        .join('\n');

    const rtf = `{\\rtf1\\ansi\\deff0
{\\fonttbl{\\f0 Arial;}}
{\\colortbl ;\\red30\\green64\\blue175;}
\\f0\\fs20
{\\b\\fs28\\cf1 ${rtfEscape(title)}}\\par
{\\fs18 Generated: ${new Date().toLocaleString('en-KE')}}\\par\\par
${headerRow}
${dataRows}
}`;

    const blob = new Blob([rtf], { type: 'application/rtf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.rtf`;
    a.click();
    URL.revokeObjectURL(url);
}

/** Unified export dispatcher */
export function exportReport({ format, ...opts }) {
    switch (format) {
        case 'pdf':
            return exportToPDF(opts);
        case 'excel':
        case 'csv':
            return exportToExcel(opts);
        case 'rtf':
            return exportToRTF(opts);
        default:
            exportToPDF(opts);
    }
}
